[build]
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.10"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
